# Build the container
link:
	cd ../../addons/actions ; yarn link
	yarn link @storybook/addon-actions

	cd ../../addons/links ; yarn link
	yarn link @storybook/addon-links

	cd ../../addons/knobs ; yarn link
	yarn link @storybook/addon-knobs

	cd ../../lib/addons ; yarn link ;
	yarn link @storybook/addons

	cd ../../lib/channel-postmessage ; yarn link ;
	yarn link @storybook/channel-postmessage

	cd ../../lib/channels ; yarn link ;
	yarn link @storybook/channels

	cd ../../lib/ui ; yarn link ;
	yarn link @storybook/ui

	cd ../../lib/ui ; yarn link ;
	yarn link @storybook/ui

	cd ../../lib/components ; yarn link ;
	yarn link @storybook/components

unlink:
	yarn unlink @storybook/ui
